apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # Use ClusterRoleBinding if using ClusterRole
metadata:
  name: github-actions-deployer-binding
  namespace: default # Must match the Role and ServiceAccount's namespace
subjects:
- kind: ServiceAccount
  name: github-actions-user
  namespace: default # Must match the ServiceAccount's namespace
roleRef:
  kind: Role # Must match the kind of role created above (Role or ClusterRole)
  name: github-actions-deployer
  apiGroup: rbac.authorization.k8s.io
