name: CICD Pipeline
on:
   push:
      branches: "main"
   pull_request:
      branches: "main"
jobs:
   build:
      runs-on: self-hosted
      
      steps:
        - uses: actions/checkout@v4
        
        # - name: build with maven
        #   # if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        #   run: mvn clean install -B

        - name: echo command
          run: echo "result:${{ env.FULL_COMMAND }}"

        - name: Install Docker Buildx Plugin
          run: |
            mkdir -p ~/.docker/cli-plugins
            curl -L https://github.com/docker/buildx/releases/download/v0.10.0/buildx-v0.10.0-linux-amd64 > ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx

        - name: Enable Docker BuildKit
          run: |
            export DOCKER_BUILDKIT=1
            docker buildx version
          
        - name: build and deploy in dockerhub
          env:
            DOCKER_REGISTRY: docker.io
            DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
            IMAGE_NAME: jaijp/sms
            
          run: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
            docker build -t jaijp/sms:latest .
            docker push jaijp/sms:latest
            docker logout $DOCKER_REGISTRY
            
