name: CICD Pipeline
on:
   push:
      branches: "main"
   pull_request:
      branches: "main"
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v4
        
        - name: build with maven
          if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
          run: mvn clean install -B

          
        - name: build and deploy in dockerhub
          run:
            docker login -u @DOCKER_USERNAME -p @DOCKER_PASSWORD $DOCKER_REGISTRY
            docker build -t jaijp/sms:latest .
            docker push jaijp/sms:latest
            docker logout $DOCKER_REGISTRY
            
