name: CICD Pipeline
on:
   push:
      branches: "main"
   pull_request:
      branches: "main"
jobs:
   build:
      runs-on: self-hosted
      
      steps:
        - uses: actions/checkout@v4
        
        # - name: build with maven
        #   # if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        #   run: mvn clean install -B

        - name: echo command
          run: echo "result:${{ env.FULL_COMMAND }}"

        # - name: Install Docker Buildx Plugin
        #   run: |
        #      # Buildx 0.6+
        #      docker buildx bake "https://github.com/docker/buildx.git"
        #      mkdir -p ~/.docker/cli-plugins
        #      mv ./bin/build/buildx ~/.docker/cli-plugins/docker-buildx

        #      # Docker 19.03+
        #      DOCKER_BUILDKIT=1 docker build --platform=local -o . "https://github.com/docker/buildx.git"
        #      mkdir -p ~/.docker/cli-plugins
        #      mv buildx ~/.docker/cli-plugins/docker-buildx

        #      # Local
        #      git clone https://github.com/docker/buildx.git && cd buildx
        #      make install
          
        - name: build and deploy in dockerhub
          env:
            DOCKER_REGISTRY: docker.io
            DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
            IMAGE_NAME: jaijp/sms
            
          run: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
            docker build -t jaijp/sms:latest .
            docker push jaijp/sms:latest
            docker logout $DOCKER_REGISTRY
            
